# Look into the Emscripten default include path thing, rather than setting
# these manually.
set(CMAKE_SYSTEM_NAME Emscripten)
set(CMAKE_SYSTEM_PROCESSOR x86)
set(CMAKE_CROSSCOMPILING ON)

if (NOT EMSCRIPTEN_PREFIX)
  set(EMSCRIPTEN_PREFIX /usr/lib/emscripten)
  if (DEFINED ENV{EMSCRIPTEN})
    set(EMSCRIPTEN_PREFIX $ENV{EMSCRIPTEN})
  elseif (DEFINED ENV{EMSCRIPTEN_ROOT})
    set(EMSCRIPTEN_PREFIX $ENV{EMSCRIPTEN_ROOT})
  endif()
endif ()

unset(WIN32)
unset(APPLE)
set(UNIX 1)

set(EMSCRIPTEN_TOOLCHAIN_PATH "${EMSCRIPTEN_PREFIX}/system")

set(CMAKE_C_COMPILER "${EMSCRIPTEN_PREFIX}/emcc")
set(CMAKE_CXX_COMPILER "${EMSCRIPTEN_PREFIX}/em++")
set(CMAKE_AR "${EMSCRIPTEN_PREFIX}/emar" CACHE FILEPATH "Emscripten archive")
set(CMAKE_RANLIB "${EMSCRIPTEN_PREFIX}/emranlib" CACHE FILEPATH "Emscripten ranlib")

list(APPEND CMAKE_FIND_ROOT_PATH ${EMSCRIPTEN_TOOLCHAIN_PATH} ${EMSCRIPTEN_PREFIX})

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_CXX_FLAGS_RELEASE_INIT "-DNDEBUG -O3")
set(CMAKE_CXX_FLAGS_INIT "-s WASM=1")

set(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "-O3 --llvm-lto 1")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-s WASM=1")
