include_guard(GLOBAL)

function (check_component package component)
  set(found ON)
  foreach (item IN LISTS ${ARGN})
    if (NOT item)
      set(found OFF)
      break()
    endif()
  endforeach ()
  set(${package}_${component}_FOUND ${found} PARENT_SCOPE)
endfunction ()

function (check_library_component package component)
  set(combined ${package}_${component})
  set(library ${combined}_LIBRARY)
  check_component(${package} ${component} ${library})
  set(${combined}_FOUND ${${combined}_FOUND} PARENT_SCOPE)
endfunction()

function (check_program_component package component)
  set(combined ${package}_${component})
  set(executable ${combined}_EXECUTABLE)
  check_program_component(${package} ${component} ${executable})
  set(${combined}_FOUND ${${combined}_FOUND} PARENT_SCOPE)
endfunction()
